#!/usr/bin/env bun
// Merge every crosswalk/<area>.csv into ALL.csv using a real RFC-4180 parser
// (handles quoted fields with embedded commas/newlines, and missing trailing newlines).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = import.meta.dir;
const FILES = [
  "lab.csv",
  "vital.csv",
  "problem.csv",
  "medication.csv",
  "immunization.csv",
  "allergy.csv",
  "observation-coded.csv",
  "other-coded.csv",
  // Epic-instance-OID codings (TODO #3): the non-standard OID/ATC codings the
  // reference carries in the SAME code.coding[] arrays as the standard codes,
  // anchored to the SAME EHI local code. Generated by build-epic-instance-oid.ts.
  "epic-instance-oid.csv",
];

// RFC-4180 parser -> array of rows, each row an array of fields.
export function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let field = "";
  let row: string[] = [];
  let i = 0;
  let inQuotes = false;
  const n = text.length;
  while (i < n) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; continue; }
        inQuotes = false; i++; continue;
      }
      field += c; i++; continue;
    }
    if (c === '"') { inQuotes = true; i++; continue; }
    if (c === ",") { row.push(field); field = ""; i++; continue; }
    if (c === "\r") { i++; continue; }
    if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; i++; continue; }
    field += c; i++;
  }
  // flush trailing field/row if file did NOT end in a newline
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows;
}

function csvField(v: string): string {
  if (/[",\n\r]/.test(v)) return '"' + v.replace(/"/g, '""') + '"';
  return v;
}

function main() {
let header: string[] | null = null;
const allDataRows: string[][] = [];
const partCounts: Record<string, number> = {};

for (const f of FILES) {
  const text = readFileSync(join(DIR, f), "utf8");
  const rows = parseCsv(text).filter((r) => !(r.length === 1 && r[0] === ""));
  const [hdr, ...data] = rows;
  if (!header) header = hdr;
  else if (hdr.join(",") !== header.join(",")) {
    throw new Error(`Header mismatch in ${f}:\n  ${hdr.join(",")}\n vs\n  ${header.join(",")}`);
  }
  partCounts[f] = data.length;
  allDataRows.push(...data);
}

if (!header) throw new Error("no files");

const out = [header, ...allDataRows].map((r) => r.map(csvField).join(",")).join("\n") + "\n";
writeFileSync(join(DIR, "ALL.csv"), out);

const sumParts = Object.values(partCounts).reduce((a, b) => a + b, 0);
const merged = parseCsv(readFileSync(join(DIR, "ALL.csv"), "utf8"))
  .filter((r) => !(r.length === 1 && r[0] === "")).length - 1; // minus header

console.log("Per-part data rows:");
for (const f of FILES) console.log(`  ${f.padEnd(24)} ${partCounts[f]}`);
console.log(`Sum of parts : ${sumParts}`);
console.log(`Merged ALL.csv: ${merged}`);
console.log(`Match        : ${sumParts === merged ? "YES" : "NO -- MISMATCH"}`);
if (sumParts !== merged) process.exit(1);
}

if (import.meta.main) main();
