#!/usr/bin/env bun
/**
 * status.ts — the single overall STATUS scorecard. Ties together the three outcomes for every
 * target element, per resource type:
 *   EXACT     — byte-identical to the target (worked perfectly)
 *   TOLERATED — a verifying tolerance rule proved it equivalent (acceptable difference)
 *   ACCEPT    — proven floor: genuinely can't reproduce from this export (documented, with proof)
 *
 * Reads compare/LEDGER.json (run `EXCLUDE_SMARTDATA=1 bun compare/classify.ts --out=out-crosswalk`
 * first). Writes compare/STATUS.md. The per-type table reconciles: EXACT+TOLERATED+ACCEPT = elements.
 *   bun tools/status.ts
 */
import { verdict, findGaps } from "./floor-audit";

const L = JSON.parse(await Bun.file("compare/LEDGER.json").text());
const norm = (p: string) => p.replace(/\[\d+\]/g, "").replace(/\.\d+(?=\.|$)/g, "");
const perType: Record<string, { exact: number; tolerated: number; gap: number }> = L.perType || {};
const tolerated: any[] = L.toleratedDeltas || [];
const gaps: any[] = L.gaps ?? findGaps(L) ?? [];
const ruleHits: Record<string, number> = L.ruleHits || {};

const pct = (n: number, d: number) => (d ? Math.round((n / d) * 1000) / 10 : 0);

// ---- 1. headline ----
const E = L.exact, T = (L.tolerated?.total ?? tolerated.length), G = (L.gap?.total ?? gaps.length);
const total = L.totalTargetElements ?? E + T + G;
let md = `# EHI → FHIR — Overall Status Scorecard\n\n`;
md += `Generated by \`bun tools/status.ts\` from \`compare/LEDGER.json\` (crosswalk + --embed-attachments, ex-SmartData).\n`;
md += `Every target element is EXACT (perfect), TOLERATED (verified-equivalent difference), or ACCEPT (proven floor).\n\n`;
md += `| outcome | elements | % of target |\n|---|---:|---:|\n`;
md += `| **EXACT** (byte-perfect) | ${E} | ${pct(E, total)}% |\n`;
md += `| **TOLERATED** (acceptable diff) | ${T} | ${pct(T, total)}% |\n`;
md += `| **ACCEPT** (proven floor) | ${G} | ${pct(G, total)}% |\n`;
md += `| FAITHFUL (EXACT+TOLERATED) | ${E + T} | **${pct(E + T, total)}%** |\n`;
md += `| total target elements | ${total} | 100% |\n\n`;
md += `Reconciles: ${L.reconciles ? "✓" : "✗"}  ·  rules over hit-cap: ${(L.overCap || []).length}  ·  blessings pending human sign-off: ${(L.provisional || []).length}\n`;

// ---- 2. per resource type ----
md += `\n## By resource type\n\n"Perfect" = 100% EXACT. "Faithful" = EXACT+TOLERATED. Sorted by element count.\n\n`;
md += `| resource | elements | EXACT | TOLERATED | ACCEPT(floor) | faithful% | perfect? |\n|---|---:|---:|---:|---:|---:|:--:|\n`;
const rows = Object.entries(perType).map(([t, c]) => ({ t, ...c, n: c.exact + c.tolerated + c.gap })).sort((a, b) => b.n - a.n);
for (const r of rows) {
  const faithful = pct(r.exact + r.tolerated, r.n);
  const perfect = r.tolerated === 0 && r.gap === 0 ? "✅" : faithful === 100 ? "◐" : "";
  md += `| ${r.t} | ${r.n} | ${r.exact} | ${r.tolerated} | ${r.gap} | ${faithful}% | ${perfect} |\n`;
}

// ---- 3. TOLERATED — what differences we accept as equivalent, by family ----
md += `\n## TOLERATED — acceptable differences, by rule family (${T})\n\n`;
md += `Each is a NARROW verifying rule that re-derives equivalence from data and still GAPs a same-shaped regression.\n\n`;
md += `| family | hits | what it accepts |\n|---|---:|---|\n`;
const famOf = (id: string) =>
  /^iso-ref/.test(id) ? "isomorphic reference (synthetic vs Epic-opaque id, same entity)"
  : /^cosmetic-display|^cosmetic-case/.test(id) ? "cosmetic display/case (same coded concept, different label casing/wording)"
  : /minute-rounded/.test(id) ? "minute-precision instant (export rounds *_DTTM to the minute)"
  : /encounter-class/.test(id) ? "Encounter.class standard v3-ActCode vs Epic-local code (same concept)"
  : /attachment/.test(id) ? "attachment Binary url/contentType (content-hash bound, same note)"
  : /version|server-artifact|server-stamp/.test(id) ? "server-stamped artifact (versionId / ValueSet version)"
  : /blessed/.test(id) ? "blessed value (human-pinned exact pair)"
  : "other";
const famTally: Record<string, number> = {};
for (const [id, n] of Object.entries(ruleHits)) if (n > 0) famTally[famOf(id)] = (famTally[famOf(id)] || 0) + n;
for (const [f, n] of Object.entries(famTally).sort((a, b) => b[1] - a[1])) md += `| ${f.split(" (")[0]} | ${n} | ${f.includes("(") ? f.slice(f.indexOf("(") + 1, -1) : f} |\n`;

// ---- 4. ACCEPT — proven floor, by theme (root cause) ----
md += `\n## ACCEPT — proven floor, by root cause (${G})\n\n`;
md += `Each cluster carries a one-line GROUP-BY proof in \`compare/CODING-FLOOR-AUDIT.md\`. Grouped here by why it can't be reproduced.\n\n`;
const themeOf = (note: string) =>
  /ENC_TYPE_C|visit-type|enc-type/.test(note) ? "Epic visit-type dictionary not exported (ENC_TYPE_C)"
  : /flowsheet|LOINC|\.96|grep=0|SNOMED.*sitting|measure\/value-type/.test(note) ? "Epic flowsheet/value terminology maps not exported"
  : /role|Signer|Clerk|context\/role|note context/.test(note) ? "Epic note role/context dictionary not exported"
  : /DX_ID->SNOMED|DX_ID→SNOMED|indication SNOMED|reasonCode SNOMED/.test(note) ? "no DX_ID→SNOMED map in export"
  : /masked|privacy|redact|truthful full name/.test(note) ? "privacy masking / intentional PHI redaction (we emit truthful)"
  : /truthful EHI label|RxNorm|cased variant|drug name|codeless|expanded list|component label|admit-source label/.test(note) ? "truthful EHI value vs Epic display transform (cosmetic)"
  : /no ZC form-master|ORDER_CLASS uniformly|courseOfTherapy|\bform\b/.test(note) ? "med form/course master not exported"
  : /comparator artifact|duplicate-per-SER|API-only|not surfaced by Epic|curation|no parent row|panel-grouper|hasMember/.test(note) ? "Epic-API curation / comparator artifact (no standalone EHI row)"
  : /appointment slot end|no DEPARTMENT_ID|source linkage absent|no provider-status|accidentrelated|admitSource|dischargeDisposition|opaque|non-bijective|server|doseAndRate.*calculated|absent/.test(note) ? "datum/linkage genuinely absent from export"
  : "other (see CODING-FLOOR-AUDIT.md)";
const themeTally: Record<string, number> = {};
const themeEx: Record<string, string> = {};
for (const g of gaps) {
  const [v, note] = verdict(g);
  const th = themeOf(note);
  themeTally[th] = (themeTally[th] || 0) + 1;
  if (!themeEx[th]) themeEx[th] = `${g.rt}.${norm(g.path)}`;
}
md += `| root cause | leaves | example path |\n|---|---:|---|\n`;
for (const [th, n] of Object.entries(themeTally).sort((a, b) => b[1] - a[1])) md += `| ${th} | ${n} | \`${themeEx[th]}\` |\n`;

md += `\n---\nDrill-down: \`compare/TRIAGE.md\` (FIX/TOLERATE/ACCEPT per cluster) · \`compare/CODING-FLOOR-AUDIT.md\` (per-cluster floor proofs) · \`compare/TOLERANCES.md\` (every tolerance rule + the regression it rejects) · \`gaps/<domain>.md\` (per-domain narrative).\n`;

await Bun.write("compare/STATUS.md", md);
console.log(`EXACT ${E} (${pct(E, total)}%) | TOLERATED ${T} | ACCEPT ${G} | faithful ${pct(E + T, total)}% of ${total}`);
console.log("wrote compare/STATUS.md");
