#!/usr/bin/env bun
/**
 * triage.ts — the disposition ledger. Every remaining GAP leaf is assigned EXACTLY ONE of:
 *   FIX      — a generator/crosswalk change will close it (becomes EXACT). OPEN work.
 *   TOLERATE — a verifying tolerance will absorb it (becomes TOLERATED). OPEN work.
 *   ACCEPT   — proven floor: genuinely absent/not-reproducible from THIS export. CLOSED.
 *
 * SINGLE SOURCE OF TRUTH: the disposition is DERIVED from tools/floor-audit.ts `verdict()`
 * (the maintained, GROUP-BY-proof-carrying adjudication), remapped:
 *   FLOOR   -> ACCEPT (closed, proven)
 *   MOVABLE -> TOLERATE if its note names a tolerance (cosmetic/iso-ref/display/case/version),
 *              else FIX (generator/crosswalk action)
 *   UNSURE  -> FIX:investigate (never silently parked — unknowns are explicit open work)
 *
 * OPEN BACKLOG = FIX + TOLERATE. Goal: drive OPEN -> 0, leaving only the ACCEPT set.
 *   bun tools/triage.ts        # reads compare/LEDGER.json, writes compare/TRIAGE.md
 */
import { verdict, findGaps } from "./floor-audit";

const L = JSON.parse(await Bun.file("compare/LEDGER.json").text());
const gaps = L.gaps ?? findGaps(L);
const norm = (p: string) => p.replace(/\[\d+\]/g, "").replace(/\.\d+(?=\.|$)/g, "");

const TOLERATE_RE = /toleran|cosmetic|iso-ref|display|case|version|abbrev|expansion|minute|truthful.*(cased|case)/i;
function disposition(g: any): [string, string] {
  const [v, note] = verdict(g);
  if (v === "FLOOR") return ["ACCEPT", note];
  if (v === "UNSURE") return ["FIX", "investigate (un-triaged): " + note];
  // MOVABLE -> FIX or TOLERATE by the note's named mechanism
  return [TOLERATE_RE.test(note) ? "TOLERATE" : "FIX", note];
}

const buckets: Record<string, { n: number; clusters: Record<string, { n: number; note: string }> }> = {
  FIX: { n: 0, clusters: {} }, TOLERATE: { n: 0, clusters: {} }, ACCEPT: { n: 0, clusters: {} },
};
for (const g of gaps) {
  const [d, note] = disposition(g);
  const key = g.rt + " :: " + norm(g.path || "");
  buckets[d].n++;
  (buckets[d].clusters[key] ??= { n: 0, note }).n++;
}
const openN = buckets.FIX.n + buckets.TOLERATE.n;
let md = `# Gap Triage Ledger — FIX / TOLERATE / ACCEPT\n\n`;
md += `Generated by \`bun tools/triage.ts\` (disposition derived from \`tools/floor-audit.ts\` verdict) over \`compare/LEDGER.json\` (answer-key + --embed-attachments, ex-SmartData).\n\n`;
md += `Total GAP leaves: **${gaps.length}**\n`;
md += `- **OPEN backlog (drive to 0): ${openN}** = FIX **${buckets.FIX.n}** + TOLERATE **${buckets.TOLERATE.n}**\n`;
md += `- ACCEPT (closed, proven floor): **${buckets.ACCEPT.n}**\n\n`;
md += `Every leaf has exactly one disposition; there is NO unsure bucket (unknowns default to FIX:investigate).\n`;
for (const d of ["FIX", "TOLERATE", "ACCEPT"]) {
  const b = buckets[d];
  md += `\n## ${d} — ${b.n}${d !== "ACCEPT" ? " (OPEN)" : " (closed)"}\n\n| n | cluster | disposition note |\n|---:|---|---|\n`;
  for (const [k, v] of Object.entries(b.clusters).sort((a: any, x: any) => x[1].n - a[1].n))
    md += `| ${v.n} | \`${k}\` | ${v.note} |\n`;
}
await Bun.write("compare/TRIAGE.md", md);
console.log(`GAP ${gaps.length} | OPEN ${openN} (FIX ${buckets.FIX.n} + TOLERATE ${buckets.TOLERATE.n}) | ACCEPT ${buckets.ACCEPT.n}`);
console.log("wrote compare/TRIAGE.md");
